title: C銘世界
author: Doghow
email: s9443112@gmail.com
description: >-
  先聲明一下，本篇僅供娛樂用，如果亂用裡面的照片鬧人，而抵觸相關法律、被8+9追殺等等......請自行負責，
  本人不負任何責任，請各位理性使用。如果有其它沒有收錄的、新的，私我。歡迎追蹤、卡位

social:
  twitter: s9443112
  facebook: s9443112
  instagram: tre290100
  github: s9443112
  linkedin:

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

collections:
  images:
    output: true
